state_none = {
    "away-team": "TBD",
    "home-team": "TBD",
    "away-score": "0",
    "home-score": "0",
    "inning": "0",
    "inning-half": "top",
    "outs": "0",
    "batter": "",
    "pitcher": "",
    "pitch_count": "0",
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "",
}

state_1 = {
    "away-team": "Dodgers",
    "home-team": "Padres",
    "away-score": 0,
    "home-score": 0,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Bogaerts",
    "pitcher": "Kershaw",
    "pitch_count": 0,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Middle of Inning",
}

state_2 = {
    "away-team": "Dodgers",
    "home-team": "Padres",
    "away-score": 0,
    "home-score": 0,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Bogaerts",
    "pitcher": "Kershaw",
    "pitch_count": 5,
    "count": [3, 2],
    "on_base": [None, None, None, None],
    "last-play": "Fastball - Strike",
}

state_3 = {
    "away-team": "Dodgers",
    "home-team": "Padres",
    "away-score": 0,
    "home-score": 0,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Tatis Jr.",
    "pitcher": "Kershaw",
    "pitch_count": 12,
    "count": [0, 0],
    "on_base": ["Bogaerts", None, None, None],
    "last-play": "Single",
}

state_4 = {
    "away-team": "Dodgers",
    "home-team": "Padres",
    "away-score": 0,
    "home-score": 2,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Soto",
    "pitcher": "Kershaw",
    "pitch_count": 16,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Home Run",
}

state_5 = {
    "away-team": "Dodgers",
    "home-team": "Padres",
    "away-score": 2,
    "home-score": 7,
    "inning": 9,
    "inning-half": "top",
    "outs": 1,
    "batter": "Betts",
    "pitcher": "Hader",
    "pitch_count": 4,
    "count": [2, 1],
    "on_base": ["temp", "temp", None, None],
    "last-play": "Strikeout",
}
