state_none = {
    "away-team": "TBD",
    "away-abrv": "TBD",
    "home-team": "TBD",
    "home-abrv": "TBD",
    "away-score": 0,
    "home-score": 0,
    "inning": 0,
    "inning-half": "top",
    "outs": 0,
    "batter": "",
    "pitcher": "",
    "pitch_count": 0,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "",
}

state_0 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 0,
    "home-score": 0,
    "inning": 1,
    "inning-half": "top",
    "outs": 0,
    "batter": "Betts",
    "pitcher": "Musgrove",
    "pitch_count": 0,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Game Start",
}

state_1 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 0,
    "home-score": 0,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Bogaerts",
    "pitcher": "Kershaw",
    "pitch_count": 0,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Middle of Inning",
}

state_2 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 0,
    "home-score": 0,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Bogaerts",
    "pitcher": "Kershaw",
    "pitch_count": 5,
    "count": [0, 1],
    "on_base": [None, None, None, None],
    "last-play": "Strike",
}

state_3 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 0,
    "home-score": 0,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Tatis Jr.",
    "pitcher": "Kershaw",
    "pitch_count": 7,
    "count": [0, 0],
    "on_base": ["Bogaerts", None, None, None],
    "last-play": "Single",
}

state_4 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 0,
    "home-score": 2,
    "inning": 1,
    "inning-half": "bottom",
    "outs": 0,
    "batter": "Soto",
    "pitcher": "Kershaw",
    "pitch_count": 12,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Home Run",
}

state_5 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 3,
    "inning": 7,
    "inning-half": "top",
    "outs": 2,
    "batter": "Freeman",
    "pitcher": "Musgrove",
    "pitch_count": 104,
    "count": [0, 0],
    "on_base": ["Peralta", "Heyward", "Outman", None],
    "last-play": "Walk",
}

state_6 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 3,
    "inning": 7,
    "inning-half": "top",
    "outs": 2,
    "batter": "Freeman",
    "pitcher": "Musgrove",
    "pitch_count": 105,
    "count": [0, 1],
    "on_base": ["Peralta", "Heyward", "Outman", None],
    "last-play": "Foul ball",
}

state_7 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 3,
    "inning": 7,
    "inning-half": "top",
    "outs": 2,
    "batter": "Freeman",
    "pitcher": "Musgrove",
    "pitch_count": 106,
    "count": [1, 1],
    "on_base": ["Peralta", "Heyward", "Outman", None],
    "last-play": "Ball",
}

state_8 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 3,
    "inning": 7,
    "inning-half": "top",
    "outs": 2,
    "batter": "Freeman",
    "pitcher": "Musgrove",
    "pitch_count": 107,
    "count": [2, 1],
    "on_base": ["Peralta", "Heyward", "Outman", None],
    "last-play": "Ball",
}

state_9 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 3,
    "inning": 7,
    "inning-half": "top",
    "outs": 2,
    "batter": "Freeman",
    "pitcher": "Musgrove",
    "pitch_count": 108,
    "count": [2, 2],
    "on_base": ["Peralta", "Heyward", "Outman", None],
    "last-play": "Strike",
}

state_10 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 3,
    "inning": 7,
    "inning-half": "top",
    "outs": 2,
    "batter": "Freeman",
    "pitcher": "Musgrove",
    "pitch_count": 109,
    "count": [2, 2],
    "on_base": ["Peralta", "Heyward", "Outman", None],
    "last-play": "Foul ball",
}

state_11 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 3,
    "inning": 7,
    "inning-half": "top",
    "outs": 3,
    "batter": "Freeman",
    "pitcher": "Musgrove",
    "pitch_count": 110,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Strikeout",
}

state_12 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 7,
    "inning": 9,
    "inning-half": "top",
    "outs": 1,
    "batter": "Betts",
    "pitcher": "Hader",
    "pitch_count": 9,
    "count": [2, 1],
    "on_base": ["Taylor", "Outman", None, None],
    "last-play": "Ball",
}

state_13 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 7,
    "inning": 9,
    "inning-half": "top",
    "outs": 2,
    "batter": "Freeman",
    "pitcher": "Hader",
    "pitch_count": 10,
    "count": [0, 0],
    "on_base": ["Taylor", "Outman", None, None],
    "last-play": "Popout",
}

state_14 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 7,
    "inning": 9,
    "inning-half": "top",
    "outs": 3,
    "batter": "Betts",
    "pitcher": "Hader",
    "pitch_count": 14,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Strikeout",
}

state_15 = {
    "away-team": "Dodgers",
    "away-abrv": "LAD",
    "home-team": "Padres",
    "home-abrv": "SD",
    "away-score": 2,
    "home-score": 7,
    "inning": 0,
    "inning-half": "top",
    "outs": 0,
    "batter": "",
    "pitcher": "",
    "pitch_count": 0,
    "count": [0, 0],
    "on_base": [None, None, None, None],
    "last-play": "Game End",
}